AWSTemplateFormatVersion: 2010-09-09
Description: aws-cloudwatch-dojo
Parameters:
  LambdaFunctionName:
    Description: Lambda Function Name
    Default: lambda-with-metrics2
    Type: String
  LambdaRoleName:
    Description: Lambda Role Name
    Default: lambda-with-metrics-role2
    Type: String
  LambdaPolicyName:
    Description: Policy Name
    Default: lambda-with-metrics-policy2
    Type: String
  TriggerRuleName:
    Description: Trigger Rule Name
    Default: trigger-event-rules2
    Type: String
  LambdaBucketName:
    Description: Lambda Bucket Name
    Default: lambda-metrics-bucket-yaxin
    Type: String
  LambdaBucketKey:
    Description: Lambda Bucket Key
    Default: cloudwatch-dojo2.zip
    Type: String

Resources:
  MetricsLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}
      RetentionInDays: 7

  MetricsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Role: !GetAtt MetricsLambdaRole.Arn
      Handler: src/index2.handler
      Runtime: nodejs12.x
      Code:
        S3Bucket: !Ref LambdaBucketName
        S3Key: !Ref LambdaBucketKey
      MemorySize: 128
      Timeout: 3

  MetricsLambdaRole:
    Type: AWS::IAM::Role
    DependsOn:
      - MetricsLambdaLogGroup
    Properties:
      RoleName: !Ref LambdaRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Ref LambdaPolicyName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*

  LambdaScheduleTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0/1 * * * ? *)
      Targets:
        - Id: !Ref TriggerRuleName
          Arn: !GetAtt MetricsLambda.Arn

  InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MetricsLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleTriggerRule.Arn

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AlarmSNSTopic2
      Subscription:
        - Endpoint: yxwang@thoughtworks.com
          Protocol: email
      TopicName: "SampleTopic2"

  MyMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "hello"
      LogGroupName: !Ref MetricsLambdaLogGroup
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "MyNamespace2"
          MetricName: "MyMetric2"

  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref MySNSTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      MetricName: MyMetric2
      Namespace: MyNamespace2
      OKActions:
        - !Ref MySNSTopic
      Period: 30
      EvaluationPeriods: 1
      Threshold: 1
      Statistic: Average