AWSTemplateFormatVersion: 2010-09-09
Description: Bucket for cloudwatch dojo
Parameters:
  DeploymentBucketName:
    Description: Deployment Bucket Name
    Default: lambda-metrics-bucket-yaxin
    Type: String

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DeploymentBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  DeploymentBucketName:
    Description: Deployment Bucket
    Value: !Ref DeploymentBucketName